# This file is generated by scripts/generate_homebrew_formula.sh.
class Moco < Formula
  desc "MCP Observation and Control Operator"
  homepage "https://github.com/altescy/moco"
  version "0.1.0"

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/altescy/moco/releases/download/v0.1.0/moco-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "e3107487653249d5abbd4fdb170605daf401a612d11858e373864474df699046"
    else
      url "https://github.com/altescy/moco/releases/download/v0.1.0/moco-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "a1f069e013fd9247b2f1667446c3f1c195e5e4986209d63f238528c63f8873c0"
    end
  elsif OS.linux?
    url "https://github.com/altescy/moco/releases/download/v0.1.0/moco-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "0519fa47c4bdd8ff930c3c3f3d7e2622fa1eaa39906415396e0f08421c650512"
  end

  head "https://github.com/altescy/moco.git", branch: "main"
  depends_on "rust" => :build if build.head?

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: ".")
    else
      bin.install "moco"
    end
  end

  test do
    assert_match "moco", shell_output("#{bin}/moco --help")
  end
end
