#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 <owner/repo> <tag> <metadata-dir> <output-path>" >&2
  exit 1
fi

repo="$1"
tag="$2"
metadata_dir="$3"
output_path="$4"
version="${tag#v}"

linux_asset=""
linux_sha=""
mac_arm_asset=""
mac_arm_sha=""
mac_x86_asset=""
mac_x86_sha=""

shopt -s nullglob
metadata_files=("${metadata_dir}"/*.txt)
if [[ ${#metadata_files[@]} -eq 0 ]]; then
  echo "no metadata files found in ${metadata_dir}" >&2
  exit 1
fi

for file in "${metadata_files[@]}"; do
  while IFS=$'\t' read -r target asset sha; do
    target="${target//$'\r'/}"
    asset="${asset//$'\r'/}"
    sha="${sha//$'\r'/}"
    target="${target#﻿}"
    [[ -n "${target}" ]] || continue
    case "${target}" in
      x86_64-unknown-linux-gnu)
        linux_asset="${asset}"
        linux_sha="${sha}"
        ;;
      aarch64-apple-darwin)
        mac_arm_asset="${asset}"
        mac_arm_sha="${sha}"
        ;;
      x86_64-apple-darwin)
        mac_x86_asset="${asset}"
        mac_x86_sha="${sha}"
        ;;
    esac
  done < "${file}"
done

[[ -n "${linux_asset}" && -n "${linux_sha}" ]] || {
  echo "missing release metadata for target x86_64-unknown-linux-gnu" >&2
  exit 1
}
[[ -n "${mac_arm_asset}" && -n "${mac_arm_sha}" ]] || {
  echo "missing release metadata for target aarch64-apple-darwin" >&2
  exit 1
}
[[ -n "${mac_x86_asset}" && -n "${mac_x86_sha}" ]] || {
  echo "missing release metadata for target x86_64-apple-darwin" >&2
  exit 1
}

mkdir -p "$(dirname "${output_path}")"

cat > "${output_path}" <<EOF
# This file is generated by scripts/generate_homebrew_formula.sh.
class Moco < Formula
  desc "MCP Observation and Control Operator"
  homepage "https://github.com/${repo}"
  version "${version}"

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/${repo}/releases/download/${tag}/${mac_arm_asset}"
      sha256 "${mac_arm_sha}"
    else
      url "https://github.com/${repo}/releases/download/${tag}/${mac_x86_asset}"
      sha256 "${mac_x86_sha}"
    end
  elsif OS.linux?
    url "https://github.com/${repo}/releases/download/${tag}/${linux_asset}"
    sha256 "${linux_sha}"
  end

  head "https://github.com/${repo}.git", branch: "main"
  depends_on "rust" => :build if build.head?

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: ".")
    else
      bin.install "moco"
    end
  end

  test do
    assert_match "moco", shell_output("#{bin}/moco --help")
  end
end
EOF
